# -*- coding: utf-8 -*-
"""NINA(News Intelligence Neural Analyzer).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TiE_5S-yD5U8060mPW2DpE3XDvrjWaxR

**Installing Necessary Libraries**
"""

!pip install sentence-transformers scikit-learn pandas numpy

"""**Importing Necessary Libraries**"""

import pandas as pd
import numpy as np
import re

from sentence_transformers import SentenceTransformer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score, classification_report

"""**Reading Dataset**"""

df = pd.read_csv("fake_news_dataset.csv")

# Filling null values
df['title'] = df['title'].fillna('')
df['text'] = df['text'].fillna('')

"""**Mapping Labels**"""

df['label'] = df['label'].map({
    'real': 0,
    'fake': 1
})

# Safety check
assert df['label'].isnull().sum() == 0

"""**Combining Title and Text into Content**"""

df['content'] = df['title'] + " " + df['text']

"""**Loading Model for text processing**"""

model = SentenceTransformer('all-MiniLM-L6-v2')

X = model.encode(
    df['content'].tolist(),
    batch_size=32,
    show_progress_bar=True,
    convert_to_numpy=True,
    normalize_embeddings=True
)

"""**Setting y**"""

y = df['label'].values

"""**Train-Test Split**"""

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

"""**Using Logistic Regression for classification**"""

clf = LogisticRegression(max_iter=2000, class_weight='balanced', n_jobs=-1)
clf.fit(X_train, y_train)

"""**Evaluation**"""

y_pred = clf.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))